module.exports = {
    countryName: "",
    stateName: "",
    nameName: "",
    areaName: "",

    countries: [
        {name: 'Afghanistan', code: 'AF'},  
        {name: 'Argentina', code: 'AR'}, 
        {name: 'Austria', code: 'AU'}, 
        {name: 'India', code: 'IN'}, 
        {name: 'Indonesia', code: 'ID'}, 
        {name: 'Ireland', code: 'IE'}, 
        {name: 'Maldives', code: 'MV'}, 
        {name: 'United Kingdom', code: 'GB'}, 
        {name: 'United States', code: 'US'}, 
        {name: 'Zimbabwe', code: 'ZW'} 
    ],

    allstates: [
        {name:"Ghazni", country:"Afghanistan", code: 123},
        {name:"Helmand", country:"Afghanistan", code: 123},
        {name:"Kabul", country:"Afghanistan", code: 123},
        {name:"Buenos Aires", country:"Argentina", code: 123},
        {name:"Buenos Aires Capital", country:"Argentina", code: 123},
        {name:"Burgenland", country:"Austria", code: 123},
        {name:"Salzburg", country:"Austria", code: 123},
        {name:"Vorarlberg", country:"Austria", code: 123},
        {name:"Andhra Pradesh", country:"India", code: 123},
        {name:"Assam", country:"India", code: 123},
        {name:"Bihar", country:"India", code: 123},
        {name:"New Delhi", country:"India", code: 123},
        {name:"Goa", country:"India", code: 123},
        {name:"Jharkhand", country:"India", code: 123},
        {name:"Karnataka", country:"India", code: 123},
        {name:"Maharashtra", country:"India", code: 123},
        {name:"Orissa", country:"India", code: 123},
        {name:"Rajasthan", country:"India", code: 123},
        {name:"Uttar Pradesh", country:"India", code: 123},
        {name:"Alaska", country:"United States", code: 123},
        {name:"California", country:"United States", code: 123},
        {name:"Florida", country:"IndiaUnited States", code: 123},
        {name:"Georgia", country:"United States", code: 123},
        {name:"Hawaii", country:"United States", code: 123},
        {name:"New Jersey", country:"United States", code: 123},
        {name:"New Mexico", country:"United States", code: 123},
        {name:"New York", country:"United States", code: 123},
        {name:"Oklahoma", country:"United States", code: 123},
        {name:"Texas", country:"United States", code: 123},
        {name:"Washington", country:"United States", code: 123},
           
        
    ],

    cities: [
        {name:"Jammalamadugu", state:"Andhra Pradesh"},
	    {name:"Jangaon", state:"Andhra Pradesh"},
	    {name:"Kadapa", state:"Andhra Pradesh"},
	    {name:"Kadiri", state:"Andhra Pradesh"},
	    {name:"Kagaznagar", state:"Andhra Pradesh"},
	    {name:"Kakinada", state:"Andhra Pradesh"},
	    {name:"Kalyandurg", state:"Andhra Pradesh"},
	    {name:"Kamareddy", state:"Andhra Pradesh"},
	    {name:"Kandukur", state:"Andhra Pradesh"},
	    {name:"Karimnagar", state:"Andhra Pradesh"},
        {name:"Lanka", state:"Assam"},
	    {name:"Lumding", state:"Assam"},
	    {name:"Mangaldoi", state:"Assam"},
	    {name:"Mankachar", state:"Assam"},
	    {name:"Margherita", state:"Assam"},
	    {name:"Mariani", state:"Assam"},
	    {name:"Marigaon", state:"Assam"},
	    {name:"Nagaon", state:"Assam"},
	    {name:"Nalbari", state:"Assam"},
	    {name:"North Lakhimpur", state:"Assam"},
	    {name:"Rangia", state:"Assam"},
	    {name:"Sibsagar", state:"Assam"},
	    {name:"Silapathar", state:"Assam"},
	    {name:"Silchar", state:"Assam"},
	    {name:"Tezpur", state:"Assam"},
        {name:"Arrah", state:"Bihar"},
        {name:"Aurangabad", state:"Bihar"},
        {name:"Bhagalpur", state:"Bihar"},
        {name:"Bihar Sharif", state:"Bihar"},
        {name:"Chhapra", state:"Bihar"},
        {name:"Darbhanga", state:"Bihar"},
        {name:"Daudnagar", state:"Bihar"},
        {name:"Dehri-on-Sone", state:"Bihar"},
        {name:"Gaya", "state":"Bihar"},
        {name:"Gopalganj", "state":"Bihar"},
        {name:"Patna", "state":"Bihar"},
        {name:"Kolhapur", "state":"Maharashtra"},
        {name:"Ahmednagar", "state":"Maharashtra"},
        {name:"Akola", "state":"Maharashtra"},
        {name:"Amravati", "state":"Maharashtra"},
        {"name":"Aurangabad", "state":"Maharashtra"},
        {"name":"Baramati", "state":"Maharashtra"},
        {"name":"Chalisgaon", "state":"Maharashtra"},
        {"name":"Chinchani", "state":"Maharashtra"},
        {"name":"Devgarh", "state":"Maharashtra"},
        {"name":"Dhule", "state":"Maharashtra"},
        {"name":"Dombivli", "state":"Maharashtra"},
        {"name":"Durgapur", "state":"Maharashtra"},
        {"name":"Ichalkaranji", "state":"Maharashtra"},
        {"name":"Jalna", "state":"Maharashtra"},
        {"name":"Kalyan", "state":"Maharashtra"},
        {"name":"Latur", "state":"Maharashtra"},
        {"name":"Loha", "state":"Maharashtra"},
        {"name":"Lonar", "state":"Maharashtra"},
        {"name":"Lonavla", "state":"Maharashtra"},
        {"name":"Mahad", "state":"Maharashtra"},
        {"name":"Mahuli", "state":"Maharashtra"},
        {"name":"Malegaon", "state":"Maharashtra"},
        {"name":"Malkapur", "state":"Maharashtra"},
        {"name":"Manchar", "state":"Maharashtra"},
        {"name":"Mangalvedhe", "state":"Maharashtra"},
        {"name":"Mangrulpir", "state":"Maharashtra"},
        {"name":"Manjlegaon", "state":"Maharashtra"},
        {"name":"Manmad", "state":"Maharashtra"},
        {"name":"Manwath", "state":"Maharashtra"},
        {"name":"Mehkar", "state":"Maharashtra"},
        {"name":"Mhaswad", "state":"Maharashtra"},
        {"name":"Miraj", "state":"Maharashtra"},
        {"name":"Morshi", "state":"Maharashtra"},
        {"name":"Mukhed", "state":"Maharashtra"},
        {"name":"Mul", "state":"Maharashtra"},
        {"name":"Mumbai", "state":"Maharashtra"},
        {"name":"Murtijapur", "state":"Maharashtra"},
        {"name":"Nagpur", "state":"Maharashtra"},
        {"name":"Nalasopara", "state":"Maharashtra"},
        {"name":"Nanded-Waghala", "state":"Maharashtra"},
        {"name":"Nandgaon", "state":"Maharashtra"},
        {"name":"Anugul", "state":"Orissa"},
        {"name":"Asika", "state":"Orissa"},
        {"name":"Balangir", "state":"Orissa"},
        {"name":"Balasore", "state":"Orissa"},
        {"name":"Baleshwar", "state":"Orissa"},
        {"name":"Bamra", "state":"Orissa"},
        {"name":"Barbil", "state":"Orissa"},
        {"name":"Bargarh", "state":"Orissa"},
        {"name":"Bargarh", "state":"Orissa"},
        {"name":"Baripada", "state":"Orissa"},
        {"name":"Basudebpur", "state":"Orissa"},
        {"name":"Belpahar", "state":"Orissa"},
        {"name":"Bhadrak", "state":"Orissa"},
        {"name":"Bhawanipatna", "state":"Orissa"},
        {"name":"Bhuban", "state":"Orissa"},
        {"name":"Bhubaneswar", "state":"Orissa"},
        {"name":"Biramitrapur", "state":"Orissa"},
        {"name":"Brahmapur", "state":"Orissa"},
        {"name":"Brajrajnagar", "state":"Orissa"},
        {"name":"Byasanagar", "state":"Orissa"},
        {"name":"Cuttack", "state":"Orissa"},
        {"name":"Debagarh", "state":"Orissa"},
        {"name":"Dhenkanal", "state":"Orissa"},
        {"name":"Gunupur", "state":"Orissa"},
        {"name":"Hinjilicut", "state":"Orissa"},
        {"name":"Jagatsinghapur", "state":"Orissa"},
        {"name":"Jajapur", "state":"Orissa"},
        {"name":"Jaleswar", "state":"Orissa"},
        {"name":"Jatani", "state":"Orissa"},
        {"name":"Zirakpur", "state":"Punjab"},
        {"name":"Bali", "state":"Rajasthan"},
        {"name":"Banswara", "state":"Rajastan"},
        {"name":"Ajmer", "state":"Rajasthan"},
        {"name":"Alwar", "state":"Rajasthan"},
        {"name":"Bandikui", "state":"Rajasthan"},
        {"name":"Baran", "state":"Rajasthan"},
        {"name":"Barmer", "state":"Rajasthan"},
        {"name":"Bikaner", "state":"Rajasthan"},
        {"name":"Fatehpur", "state":"Rajasthan"},
        {"name":"Jaipur", "state":"Rajasthan"},
        {"name":"Jaisalmer", "state":"Rajasthan"},
        {"name":"Jodhpur", "state":"Rajasthan"},
        {"name":"Kota", "state":"Rajasthan"},
        {"name":"Lachhmangarh", "state":"Rajasthan"},
        {"name":"Ladnu", "state":"Rajasthan"},
        {"name":"Lakheri", "state":"Rajasthan"},
        {"name":"Lalsot", "state":"Rajasthan"},
        {"name":"Losal", "state":"Rajasthan"},
        {"name":"Makrana", "state":"Rajasthan"},
        {"name":"Malpura", "state":"Rajasthan"},
        {"name":"Mandalgarh", "state":"Rajasthan"},
        {"name":"Mandawa", "state":"Rajasthan"},
        {"name":"Mangrol", "state":"Rajasthan"},
        {"name":"Merta name", "state":"Rajasthan"},
        {"name":"Mount Abu", "state":"Rajasthan"},
        {"name":"Nadbai", "state":"Rajasthan"},
        {"name":"Nagar", "state":"Rajasthan"},
        {"name":"Nagaur", "state":"Rajasthan"},
        {"name":"Nargund", "state":"Rajasthan"},
        {"name":"Nasirabad", "state":"Rajasthan"},
        {"name":"Nathdwara", "state":"Rajasthan"},
        {"name":"Navalgund", "state":"Rajasthan"},
        {"name":"Nawalgarh", "state":"Rajasthan"},
        {"name":"Neem-Ka-Thana", "state":"Rajasthan"},
        {"name":"Nelamangala", "state":"Rajasthan"},
        {"name":"Nimbahera", "state":"Rajasthan"},
        {"name":"Nipani", "state":"Rajasthan"},
        {"name":"Niwai", "state":"Rajasthan"},
        {"name":"Nohar", "state":"Rajasthan"},
        {"name":"Nokha", "state":"Rajasthan"},
        {"name":"Pali", "state":"Rajasthan"},
        {"name":"Phalodi", "state":"Rajasthan"},
        {"name":"Phulera", "state":"Rajasthan"},
        {"name":"Pilani", "state":"Rajasthan"},
        {"name":"Pilibanga", "state":"Rajasthan"},
        {"name":"Pindwara", "state":"Rajasthan"},
        {"name":"Pipar name", "state":"Rajasthan"},
        {"name":"Prantij", "state":"Rajasthan"},
        {"name":"Amlabad", "state":"Jharkhand"},
        {"name":"Ara", "state":"Jharkhand"},
        {"name":"Barughutu", "state":"Jharkhand"},
        {"name":"Bokaro Steel name", "state":"Jharkhand"},
        {"name":"Chaibasa", "state":"Jharkhand"},
        {"name":"Chakradharpur", "state":"Jharkhand"},
        {"name":"Chandrapura", "state":"Jharkhand"},
        {"name":"Chatra", "state":"Jharkhand"},
        {"name":"Chirkunda", "state":"Jharkhand"},
        {"name":"Churi", "state":"Jharkhand"},
        {"name":"Daltonganj", "state":"Jharkhand"},
        {"name":"Deoghar", "state":"Jharkhand"},
        {"name":"Dhanbad", "state":"Jharkhand"},
        {"name":"Dumka", "state":"Jharkhand"},
        {"name":"Garhwa", "state":"Jharkhand"},
        {"name":"Ghatshila", "state":"Jharkhand"},
        {"name":"Giridih", "state":"Jharkhand"},
        {"name":"Godda", "state":"Jharkhand"},
        {"name":"Gomoh", "state":"Jharkhand"},
        {"name":"Gumia", "state":"Jharkhand"},
        {"name":"Gumla", "state":"Jharkhand"},
        {"name":"Hazaribag", "state":"Jharkhand"},
        {"name":"Hussainabad", "state":"Jharkhand"},
        {"name":"Jamshedpur", "state":"Jharkhand"},
        {"name":"Jamtara", "state":"Jharkhand"},
        {"name":"Jhumri Tilaiya", "state":"Jharkhand"},
        {"name":"Khunti", "state":"Jharkhand"},
        {"name":"Lohardaga", "state":"Jharkhand"},
        {"name":"Madhupur", "state":"Jharkhand"},
        {"name":"Mihijam", "state":"Jharkhand"},
        {"name":"Musabani", "state":"Jharkhand"},
        {"name":"Pakaur", "state":"Jharkhand"},
        {"name":"Patratu", "state":"Jharkhand"},
        {"name":"Phusro", "state":"Jharkhand"},
        {"name":"Ramngarh", "state":"Jharkhand"},
        {"name":"Ranchi", "state":"Jharkhand"},
        {"name":"Sahibganj", "state":"Jharkhand"},
        {"name":"Saunda", "state":"Jharkhand"},
        {"name":"Arasikere", "state":"Karnataka"},
        {"name":"Bangalore", "state":"Karnataka"},
        {"name":"Belgaum", "state":"Karnataka"},
        {"name":"Bellary", "state":"Karnataka"},
        {"name":"Chamrajnagar", "state":"Karnataka"},
        {"name":"Chikkaballapur", "state":"Karnataka"},
        {"name":"Chintamani", "state":"Karnataka"},
        {"name":"Chitradurga", "state":"Karnataka"},
        {"name":"Gulbarga", "state":"Karnataka"},
        {"name":"Gundlupet", "state":"Karnataka"},
        {"name":"Hassan", "state":"Karnataka"},
        {"name":"Hospet", "state":"Karnataka"},
        {"name":"Hubli", "state":"Karnataka"},
        {"name":"Karkala", "state":"Karnataka"},
        {"name":"Karwar", "state":"Karnataka"},
        {"name":"Kolar", "state":"Karnataka"},
        {"name":"Asola", "state":"Delhi"},
        {"name":"Delhi", "state":"Delhi"},
        {"name":"Achhnera", "state":"Uttar Pradesh"},
        {"name":"Adari", "state":"Uttar Pradesh"},
        {"name":"Agra", "state":"Uttar Pradesh"},
        {"name":"Aligarh", "state":"Uttar Pradesh"},
        {"name":"Allahabad", "state":"Uttar Pradesh"},
        {"name":"Amroha", "state":"Uttar Pradesh"},
        {"name":"Azamgarh", "state":"Uttar Pradesh"},
        {"name":"Bahraich", "state":"Uttar Pradesh"},
        {"name":"Ballia", "state":"Uttar Pradesh"},
        {"name":"Balrampur", "state":"Uttar Pradesh"},
        {"name":"Banda", "state":"Uttar Pradesh"},
        {"name":"Bareilly", "state":"Uttar Pradesh"},
        {"name":"Chandausi", "state":"Uttar Pradesh"},
        {"name":"Dadri", "state":"Uttar Pradesh"},
        {"name":"Deoria", "state":"Uttar Pradesh"},
        {"name":"Etawah", "state":"Uttar Pradesh"},
        {"name":"Fatehabad", "state":"Uttar Pradesh"},
        {"name":"Fatehpur", "state":"Uttar Pradesh"},
        {"name":"Aldona", "state":"Goa"},
        {"name":"Curchorem Cacora", "state":"Goa"},
        {"name":"Madgaon", "state":"Goa"},
        {"name":"Mapusa", "state":"Goa"},
        {"name":"Margao", "state":"Goa"},
        {"name":"Marmagao", "state":"Goa"},
        {"name":"Panaji", "state":"Goa"},
        {"name":"Delhi", "state":"New Delhi"},
        {"name":"California City", "state":"California"},
        {"name":"Los Angeles", "state":"California"},
        {"name":"San Francisco", "state":"California"},
        {"name":"Santa Rose", "state":"California"},
        {"name":"Buffalo", "state":"New York"},
        {"name":"Syracuse", "state":"New York"},
        {"name":"Albany", "state":"New York"}

    ],

    areas: [
        {name:"Anisabad", city:"Patna", code: 123},
        {name:"Boring Road", city:"Patna", code: 123},
        {name:"Danapur", city:"Patna", code: 123},
        {name:"Fraser Road", city:"Patna", code: 123},
        {name:"Hanuman Nagar", city:"Patna", code: 123},
        {name:"Indrapuri", city:"Patna", code: 123},
        {name:"Kankarbagh", city:"Patna", code: 123},
        {name:"Jakkanpur", city:"Patna", code: 123},
        {name:"Maruti Nagar", city:"Patna", code: 123},
        {name:"Rajeev Nagar", city:"Patna", code: 123},
        {name:"Tej Pratap Nagar", city:"Patna", code: 123},
        {name:"Yadav Colony", city:"Patna", code: 123},
        {name:"A.P Colony", city:"Gaya", code: 123},
        {name:"Bata Mode", city:"Gaya", code: 123},
        {name:"Bodh Gaya", city:"Gaya", code: 123},
        {name:"Delha", city:"Gaya", code: 123},
        {name:"Gandhi Maidan", city:"Gaya", code: 123},
        {name:"Manpur", city:"Gaya", code: 123},
        {name:"Purani Godown", city:"Gaya", code: 123},
        {name:"Red Cross", city:"Gaya", code: 123},
        {name:"Station", city:"Gaya", code: 123},
        {name:"Tekari Road", city:"Gaya", code: 123},
        {name:"Ashok Nagar", city:"Ranchi", code: 123},
        {name:"Sail Satellite Colony", city:"Ranchi", code: 123},
        {name:"Resaldar Nagar", city:"Ranchi", code: 123},
        {name:"Lalpur", city:"Ranchi", code: 123},
        {name:"Harmu Housing Colony", city:"Ranchi", code: 123},
        {name:"Kantatoli Colony", city:"Ranchi", code: 123},
        {name:"Ranchi Jn", city:"Ranchi", code: 123},
        {name:"Amlabad", city:"Bokaro", code: 123},
        {name:"Bandh Dih", city:"Bokaro", code: 123},
        {name:"Bandh Dih", city:"Bokaro", code: 123},
        {name:"Bokaro (Thermal)", city:"Bokaro", code: 123},
        {name:"Bokaro Steel City", city:"Bokaro", code: 123},
        {name:"Bokaro Station", city:"Bokaro", code: 123},
        {name:"Chas", city:"Bokaro", code: 123},
        {name:"Dugda", city:"Bokaro", code: 123},
        {name:"Gomia", city:"Bokaro", code: 123},
        {name:"Phusro", city:"Bokaro", code: 123},
        {name:"Sijhua", city:"Bokaro", code: 123},
        {name:"AIIMS", city:"Delhi", code: 123},
        {name:"Arjan Garh", city:"Delhi", code: 123},
        {name:"Chandni Chowk", city:"Delhi", code: 123},
        {name:"Delhi Cantt", city:"Delhi", code: 123},
        {name:"Hauz Khas", city:"Delhi", code: 123},
        {name:"India Gate", city:"Delhi", code: 123},
        {name:"Kutub Minar", city:"Delhi", code: 123},
        {name:"Nehru Palace", city:"Delhi", code: 123},
        {name:"Patel Chowk", city:"Delhi", code: 123},
        {name:"Sarojni Nagar", city:"Delhi", code: 123},
        {name:"BEVERLY HILLS", city:"Los Angeles", code: 123},
        {name:"PASADENA", city:"Los Angeles", code: 123},
        {name:"SANTA MONICA", city:"Los Angeles", code: 123},
        {name:"THE VALLEY", city:"Los Angeles", code: 123},
        {name:"Brooklyn", city:"Los Angeles", code: 123},
        {name:"Manhattan", city:"Los Angeles", code: 123},
        {name:"Staten Island", city:"Los Angeles", code: 123},
        {name:"China Town", city:"San Francisco", code: 123},
        {name:"Golden Gate Park", city:"San Francisco", code: 123},
        {name:"Green Island", city:"Albany", code: 123}

    ]

}