module.exports = {
    exteriorFilteredTable: [],
    clickedTableCode: "",
    exteriorTableField :[    
        {Code:"USA12311",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Brooklyn",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA56781",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Green Island",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA12312",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "THE VALLEY",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND54441",
        name: "GBI cascade6",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Sumeet Raj",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND12058",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Boring Road",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA12313",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Brooklyn",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12314",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12315",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND99990",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA79237",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12378",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Boring Road",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND87650",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA76437",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA12316",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "THE VALLEY",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND97090",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12317",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Rajnish Sharma",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND12318",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Arihant Singh",
        Area: "Station",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND87690",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12319",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12321",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12322",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12323",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND84720",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND16458",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Boring Road",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA56661",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Green Island",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND90900",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA85677",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA76667",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Pemilla Sherin",
        Area: "China Town",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND10903",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Riya Jain",
        Area: "Station",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND12325",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND80980",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND80070",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA57781",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Green Island",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12326",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12327",
        name: "GBI cascade2",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Bodh Gaya",
        cost: 34567,
        title: "Apply"
        },

        {Code:"IND82350",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA63056",
        name: "GBI cascade3",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "19-06-21",
        Booked: "",
        Area: "Brooklyn",
        cost: 44568,
        title: "Apply"
        },

        {Code:"USA29956",
        name: "GBI cascade3",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Brooklyn",
        cost: 44568,
        title: "Apply"
        },


        {Code:"USA23457",
        name: "GBI cascade4",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Stephen Micheal",
        Area: "Brooklyn",
        cost: "23456",
        title: "Booked"
        },

        {Code:"USA23458",
        name: "GBI cascade5",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "THE VALLEY",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND14646",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND18844",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA58881",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Green Island",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND55667",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND70067",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND89450",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND10908",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Boring Road",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA79269",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA72679",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND34567",
        name: "GBI cascade6",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Ramesh kumar",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Booked"
        },

        {Code:"USA99891",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Green Island",
        cost: "23456",
        title: "Apply"
        },
        
        {Code:"IND45678",
        name: "GBI cascade7",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Rajesh Verma",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND82390",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA23678",
        name: "GBI cascade8",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "THE VALLEY",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA34567",
        name: "GBI cascade9",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Flemin Peter",
        Area: "THE VALLEY",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND67890",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Preeti Verma",
        Area: "Station",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND98765",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND56789",
        name: "GBI cascade2",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: 34567,
        title: "Apply"
        },

        {Code:"USA56781",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Elvin Mask",
        Area: "Green Island",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND91220",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12008",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Boring Road",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND78956",
        name: "GBI cascade3",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "22-06-21",
        Booked: "",
        Area: "Bodh Gaya",
        cost: 44568,
        title: "Apply"
        },

        {Code:"IND83330",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },


        {Code:"USA10066",
        name: "GBI cascade4",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Brooklyn",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND90400",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA56871",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Green Island",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND87654",
        name: "GBI cascade5",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND80034",
        name: "GBI cascade5",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND54321",
        name: "GBI cascade6",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA56651",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Green Island",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA79232",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA79673",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND90578",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Boring Road",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND00890",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA52251",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Green Island",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND90876",
        name: "GBI cascade7",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND88676",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA56789",
        name: "GBI cascade8",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Emiley Jessica",
        Area: "THE VALLEY",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND76543",
        name: "GBI cascade9",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "23-07-21",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12578",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND65432",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA51131",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Green Island",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND09876",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND95590",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND90008",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Boring Road",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND07654",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12333",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA59901",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Green Island",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA72090",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND23667",
        name: "GBI cascade2",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Station",
        cost: 34567,
        title: "Apply"
        },

        {Code:"USA12777",
        name: "GBI cascade3",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "15-07-21",
        Booked: "",
        Area: "THE VALLEY",
        cost: 44568,
        title: "Apply"
        },


        {Code:"IND34467",
        name: "GBI cascade4",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA27778",
        name: "GBI cascade5",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Brooklyn",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND90080",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Boring Road",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND80080",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA10077",
        name: "GBI cascade3",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "THE VALLEY",
        cost: 44568,
        title: "Apply"
        },

        {Code:"USA77757",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND45690",
        name: "GBI cascade6",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Sneha Raj",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Booked"
        },

        {Code:"USA67890",
        name: "GBI cascade8",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "THE VALLEY",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND95540",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA34567",
        name: "GBI cascade9",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Harry Smith",
        Area: "Brooklyn",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND67890",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Amrit Sri",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND88765",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND99778",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Boring Road",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND55345",
        name: "GBI cascade2",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: 34567,
        title: "Apply"
        },

        {Code:"USA14447",
        name: "GBI cascade3",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "THE VALLEY",
        cost: 44568,
        title: "Apply"
        },

        {Code:"IND86640",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA70907",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND12098",
        name: "GBI cascade3",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: 44568,
        title: "Apply"
        },


        {Code:"USA44778",
        name: "GBI cascade4",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Brooklyn",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND66678",
        name: "GBI cascade5",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Reah Hayat",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND98878",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Boring Road",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA10077",
        name: "GBI cascade3",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "THE VALLEY",
        cost: 44568,
        title: "Apply"
        },

        {Code:"IND94447",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA79117",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND58881",
        name: "GBI cascade6",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND90876",
        name: "GBI cascade7",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Bodh Gaya",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA56789",
        name: "GBI cascade8",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "THE VALLEY",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND76543",
        name: "GBI cascade9",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Prince Chopra",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Booked"
        },

        {Code:"USA73337",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "No",
        Booked: "Fleming Scott",
        Area: "China Town",
        cost: "23456",
        title: "Booked"
        },

        {Code:"IND13345",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND90090",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Buy",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND65432",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND83399",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"USA79227",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "China Town",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND09876",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Rent",
        Booked: "",
        Area: "Gandhi Maidan",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND88890",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Danapur",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND88880",
        name: "GBI cascade1",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Event",
        Booked: "",
        Area: "India Gate",
        cost: "23456",
        title: "Apply"
        },

        {Code:"IND07654",
        name: "GBI cascade10",
        Pool: "Yes",
        Garden: "Yes",
        Parking: "Yes",
        Availability: "Stay",
        Booked: "",
        Area: "Station",
        cost: "23456",
        title: "Apply"
        }
]
}